services:
  app:
    image: library-frontend
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
    volumes:
      - ./library-frontend/:/usr/src/app
    ports:
      - 3000:80
    container_name: library-frontend

  server:
    image: library-backend
    build:
      context: ./library-backend
      dockerfile: Dockerfile
    volumes:
      - ./library-backend:/usr/src/app
    ports:
      - 4000:4000
    container_name: library-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-library
    depends_on:
      - app 
      - server