post http://localhost:3003/api/login
Content-Type: application/json

{

"username": "michael",
"password": "12345"

}

###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhZWwiLCJpZCI6IjYzMGVlNjY5OTY4ZmY1YmE5OWFjMDQxYyIsImlhdCI6MTY2MTk2MDQ1MCwiZXhwIjoxNjYxOTY0MDUwfQ.zIb4blWCrHtoAyAAcGBKAQdpmQ45Pwpv51C5jrcZlbE

{

  "title": "SPAMMM I SPAMM NOW SPAMMMMMMMMMMMMM VERSION 3.0 :)",
  "author": "Michael",
  "url": "d4haha355das",
  "likes": 2

}

###
delete http://localhost:3003/api/blogs/630f82fd8cf32e38bc003e71
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhZWwiLCJpZCI6IjYzMGVlNjY5OTY4ZmY1YmE5OWFjMDQxYyIsImlhdCI6MTY2MTk2MDQ1MCwiZXhwIjoxNjYxOTY0MDUwfQ.zIb4blWCrHtoAyAAcGBKAQdpmQ45Pwpv51C5jrcZlbE


{


}